CREATE SCHEMA DATA
DROP TABLE IF EXISTS DATA.Pacienti
CREATE TABLE DATA.Pacienti (ID_PACIENT VARCHAR(50), POHLAVI VARCHAR(10), VEK_ZACATEK_HOSP INTEGER, DNY_DO_ZANIKU_VZTAHU VARCHAR(50), DUVOD_ZANIKU VARCHAR(255), DRG_KAT VARCHAR(50), DRG_NAZEV VARCHAR(255), DELKA_HOSP INTEGER, ID_ICZ VARCHAR(50), KRAJ_NAZEV VARCHAR(100), UKONCENI VARCHAR(50))
LOAD DATA FROM FILE '/data/pruchod/HB_PACIENTI_prvni_hosp_utf8.csv' INTO DATA.Pacienti USING {"from":{"file":{"header":"1", "charset":"UTF-8"}}}
DROP TABLE IF EXISTS DATA.Hospitalizace
CREATE TABLE DATA.Hospitalizace (ID_PACIENT VARCHAR(50), DRG_KAT VARCHAR(50), DRG_NAZEV VARCHAR(255), DNY_OD_ZAKLADNI_HOSP INTEGER, DELKA_HOSP INTEGER, ID_ICZ VARCHAR(50), KRAJ_NAZEV VARCHAR(100), UKONCENI VARCHAR(50))
LOAD DATA FROM FILE '/data/pruchod/HB_PACIENTI_ostatni_hosp_utf8.csv' INTO DATA.Hospitalizace USING {"from":{"file":{"header":"1", "charset":"UTF-8"}}}
DROP TABLE IF EXISTS DATA.Lazne
CREATE TABLE DATA.Lazne (ID_PACIENT VARCHAR(50), ID_ICZ VARCHAR(50), KRAJ_NAZEV VARCHAR(100), INDIKACNI_SKUPINA VARCHAR(50), NAZEV_INDIKACNI_SKUPINA VARCHAR(255), TYP_LECBY VARCHAR(50), DNY_OD_ZAKLADNI_HOSP INTEGER)
LOAD DATA FROM FILE '/data/pruchod/HB_lazne_utf8.csv' INTO DATA.Lazne USING {"from":{"file":{"header":"1", "charset":"UTF-8"}}}
DROP TABLE IF EXISTS DATA.Pece
CREATE TABLE DATA.Pece (ID_PACIENT VARCHAR(50), ID_ICZ VARCHAR(50), KRAJ_NAZEV VARCHAR(100), KODSEG VARCHAR(50), SEGMENT_NAZEV VARCHAR(255), ODB VARCHAR(50), ODB_NAZEV VARCHAR(255), TYPVYK VARCHAR(50), KOD VARCHAR(50), POCET INTEGER, NAZEV_VYKON VARCHAR(2000), DNY_OD_ZAKLADNI_PECE INTEGER, DG_TRIDA VARCHAR(50), NAZEV_DG_TRIDA VARCHAR(255), TYPDOKL VARCHAR(50), KODDOKLADU VARCHAR(50), LIM VARCHAR(50))
LOAD DATA FROM FILE '/data/pruchod/HB_pece_utf8.csv' INTO DATA.Pece USING {"from":{"file":{"header":"1", "charset":"UTF-8"}}, "pctypes":{"columntypecheck":"0"}}
DROP TABLE IF EXISTS DATA.CiselnikUkonceni
CREATE TABLE DATA.CiselnikUkonceni (KOD VARCHAR(50), POPIS VARCHAR(255))
LOAD DATA FROM FILE '/data/pruchod/Ciselnik_Ukonceni.csv' INTO DATA.CiselnikUkonceni USING {"from":{"file":{"header":"1", "charset":"UTF-8"}}}
DROP TABLE IF EXISTS DATA.CiselnikHVLP
CREATE TABLE DATA.CiselnikHVLP (KOD VARCHAR(50), NAZEV VARCHAR(500))
LOAD DATA FROM FILE '/data/pruchod/Ciselnik_HVLP.csv' INTO DATA.CiselnikHVLP USING {"from":{"file":{"header":"1", "charset":"UTF-8"}}}
DROP TABLE IF EXISTS DATA.CiselnikICZ
CREATE TABLE DATA.CiselnikICZ (ciselnik VARCHAR(255), ciselnik_kod VARCHAR(50), ciselnik_nazev VARCHAR(255), ICZ_IRI VARCHAR(255), ICZ VARCHAR(50), ICZ_nazev VARCHAR(255), ICO VARCHAR(50), ICO_nazev VARCHAR(255), adresa_RUIAN VARCHAR(50), okres_RUIAN VARCHAR(50), adresa_nestr VARCHAR(255), ROS_datum_vzniku_opravneni VARCHAR(50), ROS_datum_zaniku_opravneni VARCHAR(50), NRPZS_druh_poskytovatele_kod VARCHAR(50), NRPZS_datum_zahajeni_cinnosti VARCHAR(50), NRPZS_datum_ukonceni_cinnosti VARCHAR(50))
LOAD DATA FROM FILE '/data/pruchod/Ciselnik_ICZ.csv' INTO DATA.CiselnikICZ USING {"from":{"file":{"header":"1", "charset":"UTF-8"}}}

-- Create indexes for performance
CREATE INDEX idx_hospitalizace_patient ON DATA.Hospitalizace (ID_PACIENT)
CREATE INDEX idx_lazne_patient ON DATA.Lazne (ID_PACIENT)
CREATE INDEX idx_pece_patient ON DATA.Pece (ID_PACIENT)

-- Create table for Vector Embeddings
DROP TABLE IF EXISTS DATA.PatientEmbeddings
CREATE TABLE DATA.PatientEmbeddings (
    ID_PACIENT VARCHAR(50),
    Embedding VECTOR(DECIMAL, 384)
)
