// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetPatientEwsPatientsPatientIdEwsGetData, GetPatientEwsPatientsPatientIdEwsGetErrors, GetPatientEwsPatientsPatientIdEwsGetResponses, GetPatientFuturesPatientsPatientIdFuturesGetData, GetPatientFuturesPatientsPatientIdFuturesGetErrors, GetPatientFuturesPatientsPatientIdFuturesGetResponses, GetPatientHistoryPatientsPatientIdHistoryGetData, GetPatientHistoryPatientsPatientIdHistoryGetErrors, GetPatientHistoryPatientsPatientIdHistoryGetResponses, GetPatientPatientsPatientIdGetData, GetPatientPatientsPatientIdGetErrors, GetPatientPatientsPatientIdGetResponses, GetPatientsPatientsGetData, GetPatientsPatientsGetResponses, SuggestSuggestGetData, SuggestSuggestGetErrors, SuggestSuggestGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Suggest
 */
export const suggestSuggestGet = <ThrowOnError extends boolean = false>(options?: Options<SuggestSuggestGetData, ThrowOnError>) => (options?.client ?? client).get<SuggestSuggestGetResponses, SuggestSuggestGetErrors, ThrowOnError>({ url: '/suggest', ...options });

/**
 * Get Patients
 *
 * Get list of patients
 */
export const getPatientsPatientsGet = <ThrowOnError extends boolean = false>(options?: Options<GetPatientsPatientsGetData, ThrowOnError>) => (options?.client ?? client).get<GetPatientsPatientsGetResponses, unknown, ThrowOnError>({ url: '/patients', ...options });

/**
 * Get Patient
 *
 * Get detail of a patient
 */
export const getPatientPatientsPatientIdGet = <ThrowOnError extends boolean = false>(options: Options<GetPatientPatientsPatientIdGetData, ThrowOnError>) => (options.client ?? client).get<GetPatientPatientsPatientIdGetResponses, GetPatientPatientsPatientIdGetErrors, ThrowOnError>({ url: '/patients/{patient_id}', ...options });

/**
 * Get Patient History
 *
 * Get history of this patient
 */
export const getPatientHistoryPatientsPatientIdHistoryGet = <ThrowOnError extends boolean = false>(options: Options<GetPatientHistoryPatientsPatientIdHistoryGetData, ThrowOnError>) => (options.client ?? client).get<GetPatientHistoryPatientsPatientIdHistoryGetResponses, GetPatientHistoryPatientsPatientIdHistoryGetErrors, ThrowOnError>({ url: '/patients/{patient_id}/history', ...options });

/**
 * Get Patient Futures
 *
 * Get possible future trajectories for this patient
 */
export const getPatientFuturesPatientsPatientIdFuturesGet = <ThrowOnError extends boolean = false>(options: Options<GetPatientFuturesPatientsPatientIdFuturesGetData, ThrowOnError>) => (options.client ?? client).get<GetPatientFuturesPatientsPatientIdFuturesGetResponses, GetPatientFuturesPatientsPatientIdFuturesGetErrors, ThrowOnError>({ url: '/patients/{patient_id}/futures', ...options });

/**
 * Get Patient Ews
 *
 * Get a list of possible DRGs that could happen to this person within given time frame
 */
export const getPatientEwsPatientsPatientIdEwsGet = <ThrowOnError extends boolean = false>(options: Options<GetPatientEwsPatientsPatientIdEwsGetData, ThrowOnError>) => (options.client ?? client).get<GetPatientEwsPatientsPatientIdEwsGetResponses, GetPatientEwsPatientsPatientIdEwsGetErrors, ThrowOnError>({ url: '/patients/{patient_id}/ews', ...options });
