// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Item
 */
export type Item = {
    /**
     * Name
     */
    name: string;
    /**
     * Price
     */
    price: number;
};

/**
 * ResponseMessage
 */
export type ResponseMessage = {
    /**
     * Message
     */
    message: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetItemsItemsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/items/';
};

export type GetItemsItemsGetResponses = {
    /**
     * Response Get Items Items  Get
     *
     * Successful Response
     */
    200: Array<Item>;
};

export type GetItemsItemsGetResponse = GetItemsItemsGetResponses[keyof GetItemsItemsGetResponses];

export type CreateItemItemsPostData = {
    body: Item;
    path?: never;
    query?: never;
    url: '/items/';
};

export type CreateItemItemsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateItemItemsPostError = CreateItemItemsPostErrors[keyof CreateItemItemsPostErrors];

export type CreateItemItemsPostResponses = {
    /**
     * Successful Response
     */
    200: ResponseMessage;
};

export type CreateItemItemsPostResponse = CreateItemItemsPostResponses[keyof CreateItemItemsPostResponses];
