// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createItemItemsPost, getItemsItemsGet, type Options } from '../sdk.gen';
import type { CreateItemItemsPostData, CreateItemItemsPostError, CreateItemItemsPostResponse, GetItemsItemsGetData, GetItemsItemsGetResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getItemsItemsGetQueryKey = (options?: Options<GetItemsItemsGetData>) => createQueryKey('getItemsItemsGet', options);

/**
 * Get Items
 */
export const getItemsItemsGetOptions = (options?: Options<GetItemsItemsGetData>) => queryOptions<GetItemsItemsGetResponse, DefaultError, GetItemsItemsGetResponse, ReturnType<typeof getItemsItemsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getItemsItemsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getItemsItemsGetQueryKey(options)
});

/**
 * Create Item
 */
export const createItemItemsPostMutation = (options?: Partial<Options<CreateItemItemsPostData>>): UseMutationOptions<CreateItemItemsPostResponse, CreateItemItemsPostError, Options<CreateItemItemsPostData>> => {
    const mutationOptions: UseMutationOptions<CreateItemItemsPostResponse, CreateItemItemsPostError, Options<CreateItemItemsPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createItemItemsPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
