// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getPatientEwsPatientsPatientIdEwsGet, getPatientFuturesPatientsPatientIdFuturesGet, getPatientHistoryPatientsPatientIdHistoryGet, getPatientPatientsPatientIdGet, getPatientsPatientsGet, type Options, suggestSuggestGet } from '../sdk.gen';
import type { GetPatientEwsPatientsPatientIdEwsGetData, GetPatientEwsPatientsPatientIdEwsGetError, GetPatientEwsPatientsPatientIdEwsGetResponse, GetPatientFuturesPatientsPatientIdFuturesGetData, GetPatientFuturesPatientsPatientIdFuturesGetError, GetPatientFuturesPatientsPatientIdFuturesGetResponse, GetPatientHistoryPatientsPatientIdHistoryGetData, GetPatientHistoryPatientsPatientIdHistoryGetError, GetPatientHistoryPatientsPatientIdHistoryGetResponse, GetPatientPatientsPatientIdGetData, GetPatientPatientsPatientIdGetError, GetPatientPatientsPatientIdGetResponse, GetPatientsPatientsGetData, GetPatientsPatientsGetResponse, SuggestSuggestGetData, SuggestSuggestGetResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const suggestSuggestGetQueryKey = (options?: Options<SuggestSuggestGetData>) => createQueryKey('suggestSuggestGet', options);

/**
 * Suggest
 */
export const suggestSuggestGetOptions = (options?: Options<SuggestSuggestGetData>) => queryOptions<SuggestSuggestGetResponse, DefaultError, SuggestSuggestGetResponse, ReturnType<typeof suggestSuggestGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await suggestSuggestGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: suggestSuggestGetQueryKey(options)
});

export const getPatientsPatientsGetQueryKey = (options?: Options<GetPatientsPatientsGetData>) => createQueryKey('getPatientsPatientsGet', options);

/**
 * Get Patients
 *
 * Get list of patients
 */
export const getPatientsPatientsGetOptions = (options?: Options<GetPatientsPatientsGetData>) => queryOptions<GetPatientsPatientsGetResponse, DefaultError, GetPatientsPatientsGetResponse, ReturnType<typeof getPatientsPatientsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPatientsPatientsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPatientsPatientsGetQueryKey(options)
});

export const getPatientPatientsPatientIdGetQueryKey = (options: Options<GetPatientPatientsPatientIdGetData>) => createQueryKey('getPatientPatientsPatientIdGet', options);

/**
 * Get Patient
 *
 * Get detail of a patient
 */
export const getPatientPatientsPatientIdGetOptions = (options: Options<GetPatientPatientsPatientIdGetData>) => queryOptions<GetPatientPatientsPatientIdGetResponse, GetPatientPatientsPatientIdGetError, GetPatientPatientsPatientIdGetResponse, ReturnType<typeof getPatientPatientsPatientIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPatientPatientsPatientIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPatientPatientsPatientIdGetQueryKey(options)
});

export const getPatientHistoryPatientsPatientIdHistoryGetQueryKey = (options: Options<GetPatientHistoryPatientsPatientIdHistoryGetData>) => createQueryKey('getPatientHistoryPatientsPatientIdHistoryGet', options);

/**
 * Get Patient History
 *
 * Get history of this patient
 */
export const getPatientHistoryPatientsPatientIdHistoryGetOptions = (options: Options<GetPatientHistoryPatientsPatientIdHistoryGetData>) => queryOptions<GetPatientHistoryPatientsPatientIdHistoryGetResponse, GetPatientHistoryPatientsPatientIdHistoryGetError, GetPatientHistoryPatientsPatientIdHistoryGetResponse, ReturnType<typeof getPatientHistoryPatientsPatientIdHistoryGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPatientHistoryPatientsPatientIdHistoryGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPatientHistoryPatientsPatientIdHistoryGetQueryKey(options)
});

export const getPatientFuturesPatientsPatientIdFuturesGetQueryKey = (options: Options<GetPatientFuturesPatientsPatientIdFuturesGetData>) => createQueryKey('getPatientFuturesPatientsPatientIdFuturesGet', options);

/**
 * Get Patient Futures
 *
 * Get possible future trajectories for this patient
 */
export const getPatientFuturesPatientsPatientIdFuturesGetOptions = (options: Options<GetPatientFuturesPatientsPatientIdFuturesGetData>) => queryOptions<GetPatientFuturesPatientsPatientIdFuturesGetResponse, GetPatientFuturesPatientsPatientIdFuturesGetError, GetPatientFuturesPatientsPatientIdFuturesGetResponse, ReturnType<typeof getPatientFuturesPatientsPatientIdFuturesGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPatientFuturesPatientsPatientIdFuturesGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPatientFuturesPatientsPatientIdFuturesGetQueryKey(options)
});

export const getPatientEwsPatientsPatientIdEwsGetQueryKey = (options: Options<GetPatientEwsPatientsPatientIdEwsGetData>) => createQueryKey('getPatientEwsPatientsPatientIdEwsGet', options);

/**
 * Get Patient Ews
 *
 * Get a list of possible DRGs that could happen to this person within given time frame
 */
export const getPatientEwsPatientsPatientIdEwsGetOptions = (options: Options<GetPatientEwsPatientsPatientIdEwsGetData>) => queryOptions<GetPatientEwsPatientsPatientIdEwsGetResponse, GetPatientEwsPatientsPatientIdEwsGetError, GetPatientEwsPatientsPatientIdEwsGetResponse, ReturnType<typeof getPatientEwsPatientsPatientIdEwsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPatientEwsPatientsPatientIdEwsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPatientEwsPatientsPatientIdEwsGetQueryKey(options)
});
